### ISSUE TITLE
UI/UX: initial feedback

### ISSUE THREAD

**Issue by ProgramFOX** [Chess-Variants-Training/Chess-Variants-Training#1]
- [x] Don't show comments until you solved the puzzle.
- [x] Don't force to click 'Retry' if you fail; give a sort of "wrong move, but you can keep trying" message like lichess does.
- [x] Allow FEN input on puzzle editor.
- [x] Button to clear the editor board in one click.
- [x] Puzzle duplicate check before submitting to review.
- [x] Show board coordinates.
- [x] Password confirmation on register.

**Comment by Fortunate-MAN** [comment]
Not sure if this is the right place to make a FR, but it would be useful if you could put the `a`, `b`, `c`, `1`, `2`, `3` etc in the chess board on the website like in a real chessboard.

For example, [like over here](https://i.stack.imgur.com/XfQog.png), you can put the letters on the bottom and the top, and the numbers in the side.

**Comment by ddugovic** [comment]
The U.S. standard is to have coordinates left and below the board, like in [this article](http://blog.chesshouse.com/why-chessboards-have-algebraic-coordinates/).

**Comment by Fortunate-MAN** [comment]
@ddugovic alright. The chess board I use has coordinates on all sides, but if the standard is to have it on the left and below, I'm okay with that.

**Comment by ProgramFOX** [comment]
@Fortunate-MAN Yeah, in fact that was a piece of initial feedback that I forgot adding here. Thanks for reminding me, I added it!

**Comment by ddugovic** [comment]
All sides is cool as well, just saying if you're picking two sides those are the best to pick.

**Comment by ProgramFOX** [comment]
@ddugovic chessground's default is to have the coordinates to the right and below the board, so I'll stick with that to make things easier.
