### ISSUE TITLE
Access to puzzle database?

### ISSUE THREAD

**Issue by matt-gardner** [Chess-Variants-Training/Chess-Variants-Training#23]
Hi,

Thanks for the great site!  I've done over 1200 crazyhouse puzzles on this site, and I really enjoy it.

I have noticed a rating calibration issue on a lot of the puzzles, however, and it has made me wonder if there's a way to predict the rating just by examining the puzzle (and possibly also stockfish's analysis of it).  I have a PhD in machine learning (I wrote the [allennlp library](https://github.com/allenai/allennlp) for deep learning research in natural language processing), and I think it'd be fun to try to predict puzzle ratings.  Is there any chance I could get access to the database of puzzles, their scores, and how many times they have been attempted?

On the rating calibration issue, also: I hover around 1550 / 1600 rating for crazyhouse puzzles, and the system always gives me puzzles around that rating.  But occasionally my cookie expires, and I get served a puzzle with a random difficulty.  I find that I am frequently able to solve puzzles with ratings around 1800 when this happens, but I don't ever get served them when I'm logged in.  I'm guessing that this is just because there aren't that many users to the site, so the ratings aren't well calibrated, but it's hard to know for sure without seeing more data.

**Comment by ProgramFOX** [comment]
Sure, here's a zip: [cvt-puzzles-export-10june2019.zip](https://github.com/Chess-Variants-Training/Chess-Variants-Training/files/3270985/cvt-puzzles-export-10june2019.zip)
The zip contains one JSON file - one puzzle per line (as separate JSON objects, the whole file cannot be parsed as an array). All variants are included, you can filter them out by the "Variant" key.

The calibration issue could indeed be related to the number of users on the site (that's what I had always been assuming at least). There are thousands of crazyhouse puzzles for only a few hundred of registered users.

And please share your results when your research is done :)

**Comment by matt-gardner** [comment]
Awesome, thanks! I will definitely let you know back here when I have something interesting.
