### ISSUE TITLE
Antichess B v N endgame generator sometimes makes impossible position

### ISSUE THREAD

**Issue by ZweiSpeedruns** [Chess-Variants-Training/Chess-Variants-Training#3]
Incredibly rare, but it is possible. [Example.](http://i.imgur.com/CGYmmRs.png)

**Comment by ddugovic** [comment]
Man, that's one strange-looking rook!

**Comment by ZweiSpeedruns** [comment]
fixed title

**Comment by ddugovic** [comment]
I don't know; supposing the original title were correct, that could explain a lot (that Black's piece on g8 is supposed to be a R instead of a N).

**Comment by ZweiSpeedruns** [comment]
no, this was done in the B v N endgame trainer. My guess is that it places the two pieces randomly, assuming that it is a won endgame (which it is a bast majority of the time)
